version: '3.3'
#phpLDAPadmin page -- Login DN -- cn=admin,dc=jazz,dc=net
services:
  ldap_server:
    image: zborsos/ldap:0.0.1
    build: ./image
    environment:
      LDAP_ADMIN_PASSWORD: test1234
      LDAP_BASE_DN: dc=jazz,dc=net
      LDAP_ORGANISATION: IBM
    ports:
      - 389:389
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d
  ldap_server_admin:
    image: osixia/phpldapadmin:0.7.2
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'
volumes:
  ldap_data:
  ldap_config:
